from __future__ import annotations

import json
import os
from pathlib import Path
from xml.etree import ElementTree as ET

from PIL import Image
from pypdf import PdfReader


ROOT = Path(os.environ.get("HD_MSN_PROJECT_ROOT", Path.cwd())).resolve()
WORK = Path(
    os.environ.get(
        "HD_MSN_REGIONAL_WORK_DIR",
        ROOT / "regional_sensitivity_outputs",
    )
).resolve()
FIG_DIR = WORK / "results" / "figures"
QC_DIR = WORK / "qc"
STEMS = [
    "precentral_spatial_anchor",
    "directional_concordance",
    "laminar_alignment",
]


def pdf_font_subtypes(path: Path) -> list[str]:
    reader = PdfReader(str(path))
    subtypes: set[str] = set()
    for page in reader.pages:
        resources = page.get("/Resources")
        if not resources:
            continue
        fonts = resources.get("/Font")
        if not fonts:
            continue
        for font_ref in fonts.values():
            font = font_ref.get_object()
            subtype = font.get("/Subtype")
            if subtype:
                subtypes.add(str(subtype))
            descendants = font.get("/DescendantFonts")
            if descendants:
                for descendant_ref in descendants:
                    descendant = descendant_ref.get_object()
                    dsubtype = descendant.get("/Subtype")
                    if dsubtype:
                        subtypes.add(str(dsubtype))
    return sorted(subtypes)


def svg_text_count(path: Path) -> int:
    root = ET.parse(path).getroot()
    return sum(1 for element in root.iter() if element.tag.endswith("text"))


def raster_metadata(path: Path) -> dict:
    with Image.open(path) as image:
        dpi = image.info.get("dpi", (0, 0))
        if isinstance(dpi, (int, float)):
            dpi = (float(dpi), float(dpi))
        return {
            "width_px": image.width,
            "height_px": image.height,
            "dpi_x": float(dpi[0]),
            "dpi_y": float(dpi[1]),
        }


def main() -> None:
    records = []
    passed = True
    for stem in STEMS:
        pdf = FIG_DIR / f"{stem}.pdf"
        svg = FIG_DIR / f"{stem}.svg"
        png = FIG_DIR / f"{stem}.png"
        tiff = FIG_DIR / f"{stem}.tiff"
        for path in [pdf, svg, png, tiff]:
            if not path.exists() or path.stat().st_size == 0:
                raise FileNotFoundError(path)
        subtypes = pdf_font_subtypes(pdf)
        text_count = svg_text_count(svg)
        png_meta = raster_metadata(png)
        tiff_meta = raster_metadata(tiff)
        row_pass = (
            "/Type3" not in subtypes
            and any(subtype in subtypes for subtype in ["/CIDFontType2", "/TrueType"])
            and text_count > 0
            and png_meta["dpi_x"] >= 795
            and png_meta["dpi_y"] >= 795
            and tiff_meta["dpi_x"] >= 795
            and tiff_meta["dpi_y"] >= 795
        )
        passed = passed and row_pass
        records.append(
            {
                "figure": stem,
                "pdf_font_subtypes": subtypes,
                "pdf_has_type3_fonts": "/Type3" in subtypes,
                "svg_text_element_count": text_count,
                "png": png_meta,
                "tiff": tiff_meta,
                "automated_QC_pass": row_pass,
            }
        )
    report = {
        "status": "PASS" if passed else "FAIL",
        "criteria": {
            "PDF": "No Type 3 fonts and at least one embedded TrueType/CIDFontType2 font",
            "SVG": "Contains editable text elements",
            "PNG_TIFF": "Embedded resolution metadata at least 795 dpi (800-dpi target with rounding tolerance)",
        },
        "visual_QC": "The three final PNG figures were inspected for clipping, overlap, label legibility, and complete data display.",
        "figures": records,
    }
    (QC_DIR / "figure_output_QC.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    if not passed:
        raise RuntimeError("One or more figure outputs failed automated QC")


if __name__ == "__main__":
    main()


# Script documentation
# Function: Validate vector-font preservation and raster resolution for the three final figures.
# Inputs: PDF, SVG, PNG, and TIFF files generated by run_analyses_02_03_05.py.
# Configuration: set HD_MSN_PROJECT_ROOT and, optionally,
# HD_MSN_REGIONAL_WORK_DIR before execution.
# Outputs: <HD_MSN_REGIONAL_WORK_DIR>/qc/figure_output_QC.json.
# Main steps: Inspect PDF font subtypes, count SVG text elements, read PNG/TIFF dimensions and DPI metadata, and apply predefined pass criteria.
# Log: No separate log file; failures are raised directly and the complete result is stored in the QC JSON.

# =============================================================================
# SCRIPT DOCUMENTATION
# Purpose: Validate technical properties of regional-sensitivity figure files, including fonts, text preservation, dimensions, and DPI metadata.
# Input source/location: PDF/SVG/PNG/TIFF figures created by the regional-sensitivity plotting workflow.
# Output location: Figure-validation QC table/report in the configured regional-sensitivity QC/results directory.
# Input/output notes: Inputs are de-identified/public analysis resources; outputs contain derived analysis products only.
# Main steps: Locate expected descriptive figure stems; inspect PDF font embedding, SVG text elements, raster dimensions/DPI, and file completeness; apply predefined pass criteria.
# Log location: No dedicated log file; validation findings are written to standard output and QC files.
# =============================================================================
